on:
  workflow_dispatch:
  push:
    branches:
      - feat/azd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v0.1.0

      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login az
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set az account
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account set --subscription ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Log in with Azure
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Provision Infrastructure
        run: azd provision --no-prompt
      #   env:
      #     AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      #     AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      #     AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      #     ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      #     ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      #     RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
      #     RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
      #     RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}

      # - name: Deploy Application
      #   run: azd deploy --no-prompt
      #   env:
      #     AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      #     AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      #     AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}